url: http://kobapan.com
shopurl: https://kurakazuki.sakura.ne.jp/shop/
destination: ~/www

name: ガットポンポコ
headername: 自然農 ガットポンポコ
author:
  name: 小林 貴顕
  email: noen@kobapan.com
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap", "tables"]

permalink: /blog/:categories/:year/:month/:day/:title.html

paginate : 24
paginate_path: "blog/page:num"

tag_title_prefix: "「"
tag_title_suffix: "」 記事一覧"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
        - "/search.json"
        - "/hanbai/*"
    include_posts:
        - "/blog/index.html"

exclude: [publish.sh, shop]
