url: http://kobapan.com
shopurl: https://kobapan.com/shop/
destination: _public

name: ガットポンポコ
headername: 自然農ガットポンポコ
author:
  name: 小林 貴顕
  email: noen@kobapan.com
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap", "tables"]

permalink: /blog/:categories/:year/:month/:day/:title.html

# jekyll-toc-generator
tocTopTag: 'h2'
contentsLabel: "目次"
tocInsertElement: '.post h2:first-of-type'
tocInsertPosition: 'before'
tocInsertChildren: 'false'

paginate : 15
paginate_path: "blog/page:num"

collections:
  memo:
    output: true

tag_urls:
  自然農: sizen-nou
  食べる森: edible-forest-garden
  地域: community
  作る: make

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
        - "/search.json"
        - "/hanbai/*"
    include_posts:
        - "/blog/index.html"

exclude: [publish.sh, shop]

