url: http://0.0.0.0:4000
shopurl: https://kurakazuki.sakura.ne.jp/shop/
destination: _site

name: ガットポンポコ
headername: 自然農 ガットポンポコ
author:
  name: 小林 貴顕
  email: noen@kobapan.com
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap", "tables"]

permalink: /blog/:categories/:year/:month/:day/:title.html

paginate : 15
paginate_path: "blog/page:num"

tagurl:
  自然農: sizen-nou
  食べる森: edible-forest-garden
  地域: community
  作る: make
  see: "http://rcmdnk.github.io/blog/2016/03/15/blog-octopress/"


tag_title_prefix: "「"
tag_title_suffix: "」 記事一覧"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
        - "/search.json"
        - "/hanbai/*"
    include_posts:
        - "/blog/index.html"

exclude: [publish.sh, shop]
